### ISSUE TITLE
Consider adding a Content Security Policy to mitigate packet sniffing and XSS, and malicious browser extension consideration

### ISSUE THREAD

**Issue by mangoplane** [scholtz/wallet#41]
Hi,

I like this wallet solution.

I was just curious whether you have considered XSS in your threat model, and to consider adding CSP to protect against this. To my knowledge Vue won't automatically setup CSP. The policy tells the browser to only load images and execute scripts that come from trusted sources. Since your client is small, it might not be an issue.
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

HTTPS by itself isn't enough to prevent XSS: https://stackoverflow.com/questions/6530339/does-https-secure-cookies-prevent-xss-attacks

Also I'm curious what your thoughts are about malicious browser extensions, in relation to reading keys from WebCrypto (is that possible?), and key logging (is that possible?).

A formal analysis that addresses these points would be greatly appreciated, and assist other developers in learning.

Best regards.

**Comment by biomassives** [comment]
Im interested in working on this.  I created several educational starter projects with this codebase for our eco ops app in the past few years, and i would love to be able to give back  to the project in a significant way.

**Comment by scholtz** [comment]
```
If the site doesn't offer the CSP header, browsers likewise use the standard same-origin policy
```

I am quite aware what XSS is, and I believe there is no XSS in AWallet.. If you do not show raw data to the output, vue serialize everything so that no javascript is executable from any user input.

The data in AWallet are encrypted using AES encryption, so malicious browser extensions technically cannot read data from the indexdb.. They must somehow find the password with which user decrypts the storage for some time, and if they can do that they can obviously get the decrypted storage with all the private keys.

Btw AWallet does not use any cookies.

@mangoplane Thanks for raising the question.. I am not very familiar with CSP. 

@biomassives Feel free to analyze the codebase and/or suggest any improvements.

**Comment by scholtz** [comment]
@biomassives do you want to keep this issue open?
